---
- name: create directory, file and set timezone on all servers
  hosts: webservers, nfs, db, lb
  become: yes
  tasks:

    - name: create a directory
      file: 
        path: /home/femi-create
        state: directory

    - name: create a file
      file: 
        path: /home/femi-create/sample.txt
        state: touch

    - name: set timezone
      timezone: 
        name: America/New_York
          